name: Feature Request
description: Suggest an idea for this project
labels: ["enhancement", "triage"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: The feature request is for what package in this monorepo?
      options:
        - I’m not sure
        - next (Drupal module)
        - next-drupal (NPM package)
        - basic-starter
        - graphql-starter
        - example-auth
        - example-blog
        - example-client
        - example-custom-auth
        - example-custom-cache
        - example-custom-fetcher
        - example-custom-serializer
        - example-graphql
        - example-marketing
        - example-query
        - example-search-api
        - example-umami
        - example-webform
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the feature request
      value: |
        A clear and concise description of what the request is. If your feature request is related to a problem, please describe it.

        If applicable, add screenshots to help explain your issue.

        ### Describe the solution you'd like

        ### Describe alternatives you've considered

        ### Additional context

        Add any other context about the problem here.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        <p align="right"><em><strong>Thanks</strong> for taking the time to fill out this feature request!</em></p>
