name: Question
description: Ask a question or make a support request
labels: ["question", "triage"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: The question is for what package in this monorepo?
      options:
        - Not package-specific
        - I’m not sure
        - next (Drupal module)
        - next-drupal (NPM package)
        - basic-starter
        - graphql-starter
        - pages-starter
        - example-auth
        - example-blog
        - example-client
        - example-custom-auth
        - example-custom-cache
        - example-custom-fetcher
        - example-custom-serializer
        - example-graphql
        - example-marketing
        - example-router-migration
        - example-search-api
        - example-umami
        - example-webform
      default: 1
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Ask the question
      value: |
        A clear and concise description of what the question is.

        If applicable, add screenshots to help explain your issue.

        ### Additional context

        Add any other context about the question here.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        <p align="right"><em><strong>Thanks</strong> for taking the time to fill out this request form!</em></p>
