_core:
  default_config_hash: QdiqmcH9tjpstXqCQKv4G4rHYE4HjWLFkVzyqooqEWM
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  use_default: true
third_party_settings:
  shortcut:
    module_link: true
preset_accent_color: neutral
preset_focus_color: accent
enable_darkmode: auto
classic_toolbar: vertical
secondary_toolbar_frontend: true
high_contrast_mode: false
accent_color: "#111"
focus_color: ""
layout_density: default
show_description_toggle: false
show_user_theme_settings: false
icon_default: true
icon_path: ""
icon_upload: ""
