label: Contenido
display:
  default:
    display_title: "Por defecto"
    display_options:
      title: Contenido
      fields:
        title:
          label: Título
        type:
          label: "Tipo de contenido"
          separator: ", "
        name:
          label: Autor
        status:
          label: Estado
          settings:
            format_custom_false: "Sin publicar"
            format_custom_true: Publicado
        changed:
          label: Actualizado
        operations:
          label: Operaciones
      pager:
        options:
          tags:
            next: "Siguiente >"
            previous: "‹ Anterior"
            first: "« Primero"
            last: "Último »"
      exposed_form:
        options:
          submit_button: Filtro
          reset_button_label: Restablecer
          exposed_sorts_label: "Ordenar por"
          sort_asc_label: Asc
          sort_desc_label: Desc
      filters:
        title:
          expose:
            label: Título
        type:
          expose:
            label: "Tipo de contenido"
        status:
          expose:
            label: Estado
          group_info:
            group_items:
              1:
                title: Publicado
              2:
                title: "Sin publicar"
        langcode:
          expose:
            label: Idioma
  page_1:
    display_title: Página
    display_options:
      menu:
        title: Contenido
      tab_options:
        title: Contenido
