display:
  default:
    display_title: "Por defecto"
    display_options:
      fields:
        media_bulk_form:
          action_title: Acción
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: "Elementos por página"
            items_per_page_options_all_label: "- Todo -"
            offset_label: Desplazamiento
      exposed_form:
        options:
          reset_button_label: Restablecer
          exposed_sorts_label: "Ordenar por"
          sort_asc_label: Asc
          sort_desc_label: Desc
      filters:
        status:
          group_info:
            label: Publicado
            group_items:
              1:
                title: Publicado
              2:
                title: "Sin publicar"
        name:
          expose:
            label: Nombre
        bundle:
          expose:
            label: "Tipos multimedia"
          group_info:
            label: "Tipos multimedia"
        langcode:
          expose:
            label: Idioma
  page:
    display_title: Página
    display_options:
      fields:
        media_bulk_form:
          action_title: Acción
        name:
          separator: ", "
        edit_media:
          text: Editar
        delete_media:
          text: Eliminar
  widget:
    display_options:
      arguments:
        bundle:
          exception:
            title: Todo(s)
      filters:
        name:
          expose:
            label: Nombre
  widget_table:
    display_options:
      fields:
        name:
          label: Nombre
        uid:
          label: Autor
        changed:
          label: Actualizado
      arguments:
        bundle:
          exception:
            title: Todo(s)
      filters:
        name:
          expose:
            label: Nombre
