name: next-drupal-query
on:
  push:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test packages/next-drupal-query
