name: next-drupal
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.x'
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Run unit tests (PR)
        if: github.event_name == 'pull_request'
        run: yarn workspace next-drupal test --testPathIgnorePatterns=crud-methods --coverageThreshold='{}'
        env:
          DRUPAL_BASE_URL: http://localhost
      - name: Run all tests (main)
        if: github.event_name == 'push'
        run: yarn workspace next-drupal test
        env:
          DRUPAL_BASE_URL: ${{ secrets.DRUPAL_BASE_URL }}
          DRUPAL_USERNAME: ${{ secrets.DRUPAL_USERNAME }}
          DRUPAL_PASSWORD: ${{ secrets.DRUPAL_PASSWORD }}
          DRUPAL_CLIENT_ID: ${{ secrets.DRUPAL_CLIENT_ID }}
          DRUPAL_CLIENT_SECRET: ${{ secrets.DRUPAL_CLIENT_SECRET }}
