name: release-pr
on:
  pull_request:
    types: [labeled]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  next-drupal:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: |
      contains(github.event.pull_request.labels.*.name, format('release-pr{0} next-drupal', ':')) &&
      github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    environment: Preview
    steps:
      - name: Init
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Determine version
        uses: ./.github/version-pr
        id: determine-version
        env:
          PR_NUMBER: ${{ github.event.number }}
      - name: Publish to npm
        run: |
          cd packages/next-drupal
          yarn publish --no-git-checks --access public --tag experimental
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Comment version on PR
        env:
          VERSION: ${{ steps.determine-version.outputs.version }}
          PR_NUMBER: ${{ github.event.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment "$PR_NUMBER" --body "🎉 Experimental release [published 📦️ on npm](https://npmjs.com/package/next-drupal/v/$VERSION)!
          \`\`\`sh
          pnpm add next-drupal@$VERSION
          \`\`\`
          \`\`\`sh
          yarn add next-drupal@$VERSION
          \`\`\`
          \`\`\`sh
          npm i next-drupal@$VERSION
          \`\`\`"
